version: '3.4'

services:
  cataloguedb:
    container_name: cataloguedb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"

  catalogue.api:
    container_name: catalogue.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseSettings__ConnectionString=mongodb://cataloguedb:27017
    depends_on:
      - cataloguedb
    ports:
      - "8000:80"

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CacheSettings__ConnectionString=basketdb:6379
    depends_on:
      - basketdb
    ports:
      - "8001:80"

